import { useNavigate } from "react-router-dom";

export default function TandCPage() {
  const navigate = useNavigate();

  return (
    <main className="flex-1">
      <div className="min-h-screen bg-gradient-to-br from-gray-50 to-white">
        {/* HERO */}
        <div className="bg-gradient-to-r from-[#1cd35c] to-[#19b850] text-white py-16">
          <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
            <button
              onClick={() => navigate("/login")}
              className="mb-6 px-4 py-2 rounded-md bg-[#5DEE92] text-black font-medium hover:opacity-90 transition"
            >
              ← Go Back
            </button>

            <div className="text-center">
              <i className="lucide lucide-file-text mx-auto text-6xl mb-6 opacity-90" />
              <h1 className="text-4xl md:text-5xl font-bold mb-4">Terms of Service</h1>
              <p className="text-lg opacity-90">RoPA Application by VigilPrivacy Data</p>
              <div className="mt-4 flex justify-center gap-4">
                <span className="bg-white/20 px-4 py-2 rounded-full">Last Updated: Dec 12, 2025</span>
              </div>
            </div>
          </div>
        </div>

        {/* CONTENT */}
        <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-12 space-y-8">
          <section className="bg-white rounded-xl shadow-lg p-8">
            <p className="text-gray-700 leading-relaxed">
              Welcome to the RoPA (Record of Processing Activities) Application (“Application”), owned
              and operated by VigilPrivacy Data (“Company”, “we”, “us”, or “our”). By accessing,
              registering, or using the Application, you (“User”, “Customer”, “Organization”, “you”,
              or “your”) agree to be bound by these Terms of Service (“Terms”). These Terms create a
              legally binding agreement. If you do not agree, do not use the Application.
            </p>
          </section>

          <section className="bg-white rounded-xl shadow-lg p-8">
            <h2 className="text-2xl font-bold mb-4">1. Definitions</h2>
            <ol className="list-decimal ml-6 text-gray-700 space-y-2">
              <li>
                <strong>1.1 “Application”</strong> refers to the RoPA SaaS platform, interfaces,
                systems, tools, mobile/web versions, APIs, modules, and all associated services.
              </li>
              <li>
                <strong>1.2 “Customer Data”</strong> means all data submitted, uploaded, imported, or
                generated by you or on your behalf.
              </li>
              <li>
                <strong>1.3 “Service” / “Services”</strong> means access to the Application, features,
                and any support or maintenance services.
              </li>
              <li>
                <strong>1.4 “User Account”</strong> means an account created by an individual or
                organization to access the Application.
              </li>
              <li>
                <strong>1.5 “Applicable Laws”</strong> include the DPDPA 2023, GDPR (where applicable),
                IT Act, data protection rules, and relevant compliance standards.
              </li>
              <li>
                <strong>1.6 “Third-Party Processors”</strong> are vendors or service providers who
                support hosting, storage, analytics, or other functionalities.
              </li>
              <li>
                <strong>1.7 “Documentation”</strong> means manuals, onboarding guides, instructions, or
                support materials made available by VigilPrivacy Data.
              </li>
              <li>
                <strong>1.8 “Beta Features”</strong> means experimental or pre-release functionalities
                offered optionally.
              </li>
              <li>
                <strong>1.9 “Confidential Information”</strong> means any non-public information
                disclosed under this Agreement.
              </li>
            </ol>
          </section>

          <section className="bg-white rounded-xl shadow-lg p-8">
            <h2 className="text-2xl font-bold mb-4">2. Purpose & Scope</h2>
            <p className="text-gray-700 mb-4">
              The Application enables organizations to record, maintain, audit, export, analyse,
              and manage their Records of Processing Activities and related privacy compliance
              workflows. Features may include:
            </p>

            <ul className="list-disc ml-6 text-gray-700 space-y-1">
              <li>RoPA record management</li>
              <li>Data mapping</li>
              <li>Consent tracking</li>
              <li>Vendor/processor records</li>
              <li>Risk analysis</li>
              <li>DPIA/LIA/PIA support</li>
              <li>Compliance dashboards</li>
              <li>Reporting & exports</li>
              <li>Audit trails</li>
              <li>Metadata management</li>
            </ul>

            <p className="text-gray-700 mt-4">Use of the Application is limited to lawful compliance & business operations.</p>
          </section>

          <section className="bg-white rounded-xl shadow-lg p-8">
            <h2 className="text-2xl font-bold mb-4">3. Eligibility</h2>
            <p className="text-gray-700 mb-3">By using the Application, you confirm that:</p>

            <ul className="list-disc ml-6 text-gray-700 space-y-1">
              <li>
                <strong>Age Requirement:</strong> You are at least 18 years old and legally capable of
                entering into binding agreements.
              </li>
              <li>
                <strong>Authority:</strong> You have the necessary authority to bind your organization
                to this agreement, and you are acting on its behalf.
              </li>
              <li>
                <strong>Compliance:</strong> You will comply with all applicable laws, regulations,
                and industry standards while using the Application, including but not limited to data
                protection, privacy, and intellectual property laws.
              </li>
              <li>
                <strong>Responsible Use:</strong> You will not use the Application for any unlawful,
                harmful, or unauthorized purposes, and you agree to follow all guidelines and policies
                provided by the Application.
              </li>
              <li>
                <strong>Accuracy of Information:</strong> Any information you provide during registration
                or use of the Application is accurate, complete, and up to date.
              </li>
              <li>
                <strong>Security:</strong> You will maintain the confidentiality of your account
                credentials and promptly notify the Application provider of any unauthorized access or
                security breaches.
              </li>
            </ul>
          </section>

          <section className="bg-white rounded-xl shadow-lg p-8">
            <h2 className="text-2xl font-bold mb-4">4. Account Registration & Responsibilities</h2>
            <ol className="list-decimal ml-6 text-gray-700 space-y-2">
              <li><strong>4.1 Accurate Information:</strong> You must provide accurate, complete, and up-to-date registration information when creating an account or accessing the Application.</li>
              <li><strong>4.2 Account Security:</strong> You are solely responsible for maintaining the confidentiality and security of your login credentials. Any activity conducted under your account will be deemed authorized by you.</li>
              <li><strong>4.3 Notification of Breach:</strong> You must notify us immediately if you become aware of any unauthorized use of your account or any suspected compromise of your credentials.</li>
              <li><strong>4.4 Organizational Compliance:</strong> If you are acting on behalf of an organization, you shall ensure that all users within your organization comply with these Terms and any applicable policies.</li>
              <li><strong>4.5 Prohibition on Impersonation:</strong> You must not impersonate any person or entity, misrepresent your affiliation, or create fake or fraudulent accounts.</li>
              <li><strong>4.6 Lawful Use:</strong> You must use the Application only for lawful purposes and in accordance with all applicable laws, regulations, and contractual obligations.</li>
              <li><strong>4.7 No Misuse of Services:</strong> You must not attempt to disrupt, damage, or gain unauthorized access to the Application, its servers, or any connected systems. This includes activities such as hacking, introducing malware, or exploiting vulnerabilities.</li>
              <li><strong>4.8 Data Protection:</strong> You are responsible for ensuring that any data you upload or process through the Application complies with applicable data protection and privacy laws.</li>
              <li><strong>4.9 Intellectual Property Compliance:</strong> You must not upload, share, or use content that infringes on the intellectual property rights of others.</li>
              <li><strong>4.10 Monitoring and Auditing:</strong> You agree that we may monitor and audit your use of the Application to ensure compliance with these Terms and applicable policies.</li>
              <li><strong>4.11 Third-Party Access:</strong> You must not share your account credentials with unauthorized third parties or allow them to access the Application through your account.</li>
              <li><strong>4.12 Updates and Maintenance:</strong> You agree to keep your systems updated and compatible with the Application requirements to ensure proper functionality and security.</li>
            </ol>
          </section>

          <section className="bg-white rounded-xl shadow-lg p-8">
            <h2 className="text-2xl font-bold mb-4">5. License Grant</h2>
            <p className="text-gray-700 mb-4">
              VigilPrivacy Data grants you a limited, revocable, non-exclusive, non-transferable, and
              non-sublicensable license to access and use the Application solely for your organization’s
              internal business and compliance purposes, subject to these Terms.
            </p>

            <p className="text-gray-700 mb-4">You shall not:</p>
            <ul className="list-disc ml-6 text-gray-700 space-y-1">
              <li>Copy or Modify: Copy, reproduce, alter, adapt, translate, or create derivative works of the Application.</li>
              <li>Reverse Engineering: Attempt to reverse-engineer, decompile, or disassemble any part of the Application.</li>
              <li>Bypass Security: Attempt to disable, circumvent, or bypass any security features or access controls implemented in the Application.</li>
              <li>Compete with VigilPrivacy Data: Use the Application to develop or offer a competing product or service.</li>
              <li>Resell or Re-license: Sell, lease, sublicense, distribute, or otherwise transfer the Application or any rights granted under this Agreement.</li>
              <li>Interfere with Performance: Engage in any activity that disrupts, degrades, or interferes with the performance, integrity, or availability of the Application or its underlying infrastructure.</li>
              <li>Unauthorized Access: Access or attempt to access any data or systems without proper authorization.</li>
              <li>Use for Unlawful Purposes: Use the Application for any illegal, fraudulent, or harmful activities.</li>
            </ul>
          </section>

          <section className="bg-white rounded-xl shadow-lg p-8">
            <h2 className="text-2xl font-bold mb-4">6. Customer Data Ownership</h2>
            <p className="text-gray-700 mb-4">
              <strong>6.1 Ownership</strong><br />
              You retain full ownership and all intellectual property rights over any data, content, or information you provide or upload to the Application (“Customer Data”).
            </p>

            <p className="text-gray-700 mb-4">
              <strong>6.2 Limited Rights of Use</strong><br />
              VigilPrivacy Data does not claim any ownership rights over Customer Data. Our rights are strictly limited to what is necessary to:
            </p>

            <ul className="list-disc ml-6 text-gray-700 space-y-1">
              <li>Provide the Service and ensure its functionality.</li>
              <li>Improve system performance and enhance user experience.</li>
              <li>Protect against security threats, fraud, and abuse.</li>
              <li>Comply with legal or regulatory requirements, including responding to lawful requests from authorities.</li>
            </ul>

            <p className="text-gray-700 mb-4">
              <strong>6.3 Compliance and Legality</strong><br />
              You represent and warrant that Customer Data: does not infringe upon any third-party intellectual property rights; does not violate any applicable laws, regulations, or contractual obligations; is accurate, lawful, and free from harmful or malicious content.
            </p>

            <p className="text-gray-700 mb-4">
              <strong>6.4 Data Security</strong><br />
              VigilPrivacy Data will implement reasonable technical and organizational measures to protect Customer Data against unauthorized access, loss, or disclosure.
            </p>

            <p className="text-gray-700">
              <strong>6.5 Data Processing and Privacy</strong><br />
              Any processing of Customer Data will be carried out in accordance with our Privacy Policy and applicable data protection laws.
            </p>
          </section>

          <section className="bg-white rounded-xl shadow-lg p-8">
            <h2 className="text-2xl font-bold mb-4">7. Data Privacy & Protection</h2>
            <p className="text-gray-700">
              VigilPrivacy Data shall implement reasonable organizational, administrative, and technical safeguards to protect Customer Data and ensure the integrity of the Application. These measures include, but are not limited to:
            </p>

            <ul className="list-disc ml-6 text-gray-700 space-y-1 mt-4">
              <li>Encryption of data at rest and in transit using industry-standard protocols.</li>
              <li>Access Control & Authentication mechanisms to prevent unauthorized access.</li>
              <li>Logging & Monitoring of system activities to detect and respond to anomalies.</li>
              <li>Regular Vulnerability Assessments and security testing to identify and remediate risks.</li>
              <li>Strict Role-Based Access Permissions ensuring users have only the minimum necessary privileges.</li>
              <li>Segregation of Customer Environments to prevent data leakage or cross-contamination.</li>
            </ul>

            <p className="text-gray-700 mt-4">
              A detailed description of these measures is provided in our Privacy Policy and Security Practices documentation.
            </p>
          </section>

          <section className="bg-white rounded-xl shadow-lg p-8">
            <h2 className="text-2xl font-bold mb-4">8. Data Residency, Storage & Transfers</h2>

            <p className="text-gray-700 mb-3"><strong>8.1 Data Location</strong><br />Customer Data may be stored and processed in India or other jurisdictions permitted under applicable laws and contractual agreements.</p>

            <p className="text-gray-700 mb-3"><strong>8.2 Cross-Border Data Transfers</strong><br />If cross-border transfers of Customer Data are required, VigilPrivacy Data will ensure compliance with recognized legal frameworks, including:</p>

            <ul className="list-disc ml-6 text-gray-700 space-y-1">
              <li>Standard Contractual Clauses (SCCs) approved by relevant authorities.</li>
              <li>Adequacy Requirements under applicable data protection laws.</li>
              <li>DPDPA/GDPR-Compliant Transfer Mechanisms or equivalent safeguards.</li>
            </ul>

            <p className="text-gray-700 mt-4"><strong>8.3 Third-Party Processors</strong><br />VigilPrivacy Data may engage trusted third-party processors for purposes such as hosting and infrastructure services, analytics and performance optimization, backup and disaster recovery, integrations with authorized third-party applications. All third-party processors will be bound by contractual obligations to maintain confidentiality, security, and compliance with applicable data protection laws.</p>
          </section>

          <section className="bg-white rounded-xl shadow-lg p-8">
            <h2 className="text-2xl font-bold mb-4">9. Backups, Availability & Business Continuity</h2>

            <ul className="list-disc ml-6 text-gray-700 space-y-1">
              <li><strong>9.1 Automated Backups</strong><br />VigilPrivacy Data performs automated backups at regular intervals to help safeguard Customer Data.</li>
              <li><strong>9.2 Disaster Recovery</strong><br />We maintain disaster recovery procedures designed to restore services within reasonable time frames following an outage or system failure.</li>
              <li><strong>9.3 Downtime</strong><br />The Application may experience planned maintenance or unplanned downtime due to technical issues, updates, or circumstances beyond our control.</li>
              <li><strong>9.4 No Guarantee of Uninterrupted Service</strong><br />While we strive for high availability, VigilPrivacy Data does not guarantee uninterrupted or error-free service. Service may be affected by factors outside our reasonable control, including internet disruptions, third-party failures, or force majeure events.</li>
            </ul>
          </section>

          <section className="bg-white rounded-xl shadow-lg p-8">
            <h2 className="text-2xl font-bold mb-4">10. Acceptable Use Policy</h2>
            <p className="text-gray-700 mb-3">You agree not to engage in any of the following activities while using the Application:</p>

            <ul className="list-disc ml-6 text-gray-700 space-y-1">
              <li><strong>Upload Harmful Content</strong><br />Do not upload malware, spyware, spam, or any harmful scripts or code.</li>
              <li><strong>Unauthorized Access</strong><br />Do not attempt to gain unauthorized access to any system, account, or data.</li>
              <li><strong>Automated Tools</strong><br />Do not use bots, scrapers, or automated extraction tools to interact with the Application.</li>
              <li><strong>Illegal or Sensitive Content</strong><br />Do not upload illegal, sensitive, or prohibited content unless explicitly required for Records of Processing Activities (RoPA) compliance.</li>
              <li><strong>Unlawful Activities</strong><br />Do not use the Application for any activity that violates applicable laws, regulations, or contractual obligations.</li>
              <li><strong>Resource Abuse</strong><br />Do not introduce excessive load, disrupt performance, or abuse system resources.</li>
            </ul>

            <p className="text-gray-700 mt-3">Violation of this Acceptable Use Policy may result in immediate suspension or termination of your access to the Application without prior notice.</p>
          </section>

          <section className="bg-white rounded-xl shadow-lg p-8">
            <h2 className="text-2xl font-bold mb-4">11. Third-Party Integrations</h2>

            <p className="text-gray-700 mb-3"><strong>11.1 Integration Features</strong><br />Certain features of the Application may integrate with external applications, services, or APIs to enhance functionality.</p>

            <p className="text-gray-700 mb-3"><strong>11.2 Disclaimer of Responsibility</strong><br />VigilPrivacy Data is not responsible for: the performance, availability, or reliability of third-party systems; how third-party systems handle or process Customer Data; failures, errors, or downtime caused by integration dependencies.</p>

            <p className="text-gray-700"><strong>11.3 Third-Party Terms</strong><br />Your use of any third-party APIs, tools, or services is governed by the terms and conditions of those third parties, and you are solely responsible for compliance with such terms.</p>
          </section>

          <section className="bg-white rounded-xl shadow-lg p-8">
            <h2 className="text-2xl font-bold mb-4">12. Support, Maintenance & SLAs</h2>

            <p className="text-gray-700 mb-3"><strong>Support Includes:</strong></p>
            <ul className="list-disc ml-6 text-gray-700 space-y-1">
              <li>Email-based support for general inquiries and technical assistance.</li>
              <li>Access to a ticketing system for issue tracking and resolution.</li>
              <li>Issue resolution prioritized based on severity level.</li>
              <li>Deployment of patches, updates, and security releases as needed.</li>
            </ul>

            <p className="text-gray-700 mt-3"><strong>Indicative Response Times:</strong></p>
            <ul className="list-disc ml-6 text-gray-700 space-y-1">
              <li>Critical Issues: Response within 24 hours.</li>
              <li>High Severity: Response within 48 hours.</li>
              <li>Medium Severity: Response within 3–5 business days.</li>
              <li>Low Severity: Response within 7–10 business days.</li>
            </ul>

            <p className="text-gray-700 mt-3"><strong>Important Note:</strong> These SLA timelines are indicative only and do not constitute contractual guarantees unless a paid enterprise SLA agreement is separately executed between you and VigilPrivacy Data.</p>
          </section>

          <section className="bg-white rounded-xl shadow-lg p-8">
            <h2 className="text-2xl font-bold mb-4">13. Beta Features</h2>
            <p className="text-gray-700 mb-2"><strong>“As-Is” Basis</strong><br />Beta features are provided “as-is”, without any warranties, representations, or guarantees of performance, reliability, or fitness for a particular purpose.</p>
            <p className="text-gray-700 mb-2"><strong>Subject to Change</strong><br />Beta features may change, break, or be removed at any time without prior notice.</p>
            <p className="text-gray-700"><strong>Assumption of Risk</strong><br />By using Beta features, you assume all risks associated with their use, including potential data loss, service disruption, or incompatibility.</p>
          </section>

          <section className="bg-white rounded-xl shadow-lg p-8">
            <h2 className="text-2xl font-bold mb-4">14. Fees, Subscriptions & Payments</h2>

            <p className="text-gray-700 mb-3"><strong>14.1 Pricing and Renewal</strong><br />Details of paid plans, licensing models, and renewal cycles will be clearly stated at the time of purchase or subscription.</p>

            <p className="text-gray-700 mb-3"><strong>14.2 Non-Refundable Fees</strong><br />All fees, charges, and payments made to VigilPrivacy Data are non-refundable, except where required by applicable law.</p>

            <p className="text-gray-700 mb-3"><strong>14.3 Non-Payment Consequences</strong><br />Failure to make timely payments may result in service suspension or termination until outstanding amounts are settled.</p>

            <p className="text-gray-700"><strong>14.4 Taxes and Levies</strong><br />All applicable taxes, duties, or levies imposed by law shall be borne by the Customer, in addition to the stated fees.</p>
          </section>

          <section className="bg-white rounded-xl shadow-lg p-8">
            <h2 className="text-2xl font-bold mb-4">15. Confidentiality</h2>

            <p className="text-gray-700 mb-3">Both Parties agree to:</p>
            <ul className="list-disc ml-6 text-gray-700 space-y-1">
              <li><strong>Protect Confidential Information</strong> - Maintain the confidentiality of all proprietary or sensitive information disclosed by the other Party.</li>
              <li><strong>Restrict Disclosure</strong> - Not disclose Confidential Information to any unauthorized person or entity.</li>
              <li><strong>Limit Use</strong> - Use Confidential Information strictly for the intended business purposes under this Agreement.</li>
            </ul>

            <p className="text-gray-700 mt-3">Exceptions: The obligations above do not apply to information that is required to be disclosed under legal compulsion or by a regulatory authority; is already in the public domain without breach of this Agreement; or was lawfully obtained from a third party without confidentiality obligations.</p>
          </section>

          <section className="bg-white rounded-xl shadow-lg p-8">
            <h2 className="text-2xl font-bold mb-4">16. Security Incidents & Breach Notification</h2>

            <p className="text-gray-700 mb-3"><strong>VigilPrivacy Data Obligations</strong><br />In the event of a confirmed security incident involving Customer Data, VigilPrivacy Data will:</p>
            <ul className="list-disc ml-6 text-gray-700 space-y-1">
              <li>Notify you within a reasonable timeframe after becoming aware of the incident.</li>
              <li>Provide all known details regarding the nature and scope of the breach.</li>
              <li>Cooperate with you in remediation efforts to mitigate impact.</li>
              <li>Support you in fulfilling any legal or regulatory reporting obligations related to the incident.</li>
            </ul>

            <p className="text-gray-700 mt-3"><strong>Customer Obligations</strong><br />You must promptly notify VigilPrivacy Data if you suspect or become aware of any compromise of your account credentials or unauthorized access to the Application.</p>
          </section>

          <section className="bg-white rounded-xl shadow-lg p-8">
            <h2 className="text-2xl font-bold mb-4">17. Data Retention, Export & Deletion</h2>

            <p className="text-gray-700 mb-2"><strong>17.1 Retention During Subscription</strong><br />Customer Data will be retained for as long as your subscription remains active.</p>
            <p className="text-gray-700 mb-2"><strong>17.2 Data Export</strong><br />You may export your Customer Data at any time using the features provided within the Application.</p>
            <p className="text-gray-700"><strong>17.3 Post-Termination Handling</strong><br />Upon termination of your subscription: Access Disabled: Your access to the Application will be revoked. Export Window: You may request a data export within 30 days of termination. Deletion: Customer Data may be permanently deleted after the expiry of applicable retention windows. System Logs: Certain system logs and metadata may be retained for audit, security, and legal compliance purposes.</p>
          </section>

          <section className="bg-white rounded-xl shadow-lg p-8">
            <h2 className="text-2xl font-bold mb-4">18. Audit Rights</h2>

            <p className="text-gray-700 mb-3">Enterprise customers may request the following compliance-related artifacts from VigilPrivacy Data:</p>

            <ul className="list-disc ml-6 text-gray-700 space-y-1">
              <li>Security Compliance Reports</li>
              <li>Documentation of implemented security measures and certifications.</li>
              <li>Access Logs - Detailed logs of user and system access events, subject to applicable privacy laws.</li>
              <li>Artifacts or Attestations - Evidence of adherence to security and privacy standards.</li>
              <li>Third-Party Audit Results - Summaries or reports from independent audits conducted on VigilPrivacy Data systems.</li>
            </ul>

            <p className="text-gray-700 mt-3">Important Limitation: No physical or on-site audits shall be permitted unless expressly agreed in a separate contractual arrangement.</p>
          </section>

          <section className="bg-white rounded-xl shadow-lg p-8">
            <h2 className="text-2xl font-bold mb-4">19. Intellectual Property</h2>

            <p className="text-gray-700">All intellectual property rights related to the Application remain the exclusive property of VigilPrivacy Data, including but not limited to:</p>

            <ul className="list-disc ml-6 text-gray-700 space-y-1 mt-4">
              <li>Source Code</li>
              <li>Design and Architecture</li>
              <li>Workflow Logic</li>
              <li>UX/UI Components</li>
              <li>Documentation and Training Materials</li>
              <li>Branding and Trademarks</li>
              <li>Algorithms and Data Models</li>
              <li>Proprietary Frameworks and Tools</li>
            </ul>

            <p className="text-gray-700 mt-4">You gain no rights or ownership over these intellectual property assets other than the limited, revocable license granted under Section 5 (License and Restrictions).</p>
          </section>

          <section className="bg-white rounded-xl shadow-lg p-8">
            <h2 className="text-2xl font-bold mb-4">20. Warranties & Disclaimers</h2>

            <p className="text-gray-700 mb-3">VigilPrivacy Data does not warrant or guarantee that:</p>
            <ul className="list-disc ml-6 text-gray-700 space-y-1">
              <li>The Application will be error-free or uninterrupted.</li>
              <li>Data will never be lost, corrupted, or inaccessible.</li>
              <li>Third-party integrations will always function as expected.</li>
              <li>The Service will meet all compliance obligations of your organization.</li>
              <li>Reports or outputs generated by the Application will be legally sufficient for regulatory purposes.</li>
            </ul>

            <p className="text-gray-700 mt-3">Disclaimer: The Application is provided “as is” and “as available”, without any warranties, express or implied, including but not limited to warranties of merchantability, fitness for a particular purpose, or non-infringement.</p>
          </section>

          <section className="bg-white rounded-xl shadow-lg p-8">
            <h2 className="text-2xl font-bold mb-4">21. Limitation of Liability</h2>

            <p className="text-gray-700">To the maximum extent permitted by law:</p>
            <ul className="list-disc ml-6 text-gray-700 space-y-1 mt-3">
              <li>No Indirect or Consequential Damages - VigilPrivacy Data shall not be liable for any indirect, punitive, incidental, or consequential damages, including but not limited to loss of data, revenue, profits, or goodwill.</li>
              <li>Liability Cap - VigilPrivacy Data’s total aggregate liability under this Agreement shall be limited to the total fees paid by you in the twelve (12) months preceding the claim.</li>
              <li>Risk Assumption - You acknowledge and agree that you use the Application at your own risk, and VigilPrivacy Data does not guarantee uninterrupted service or absolute security.</li>
            </ul>
          </section>

          <section className="bg-white rounded-xl shadow-lg p-8">
            <h2 className="text-2xl font-bold mb-4">22. Indemnification</h2>

            <p className="text-gray-700">You agree to indemnify, defend, and hold harmless VigilPrivacy Data, its affiliates, officers, employees, and agents from and against any claims, damages, liabilities, costs, and expenses (including reasonable attorney fees) arising out of or related to:</p>

            <ul className="list-disc ml-6 text-gray-700 space-y-1 mt-3">
              <li>Misuse of the Application</li>
              <li>Any use of the Application in violation of these Terms or applicable laws.</li>
              <li>Illegal Data Submissions - Uploading or processing data that is unlawful, harmful, or violates third-party rights.</li>
              <li>Violation of Applicable Laws - Failure to comply with data protection, privacy, or other regulatory requirements.</li>
              <li>Breach of These Terms - Any breach of your obligations under this Agreement.</li>
              <li>Third-Party Interactions - Issues arising from your use of third-party systems, APIs, or integrations in connection with the Application.</li>
            </ul>
          </section>

          <section className="bg-white rounded-xl shadow-lg p-8">
            <h2 className="text-2xl font-bold mb-4">23. Termination</h2>

            <p className="text-gray-700 mb-3">VigilPrivacy Data may suspend or terminate your access to the Service immediately if:</p>
            <ul className="list-disc ml-6 text-gray-700 space-y-1">
              <li>You breach these Terms.</li>
              <li>You violate the Acceptable Use Policy.</li>
              <li>You misuse the Service or engage in prohibited activities.</li>
              <li>Suspension or termination is required by law or regulatory authority.</li>
            </ul>

            <p className="text-gray-700 mt-3"><strong>Customer Termination Rights:</strong> You may terminate your account at any time by following the prescribed process within the Application or by contacting support.</p>

            <p className="text-gray-700 mt-3"><strong>Effects of Termination:</strong></p>
            <ul className="list-disc ml-6 text-gray-700 space-y-1">
              <li>Access Revoked: All access to the Application will be disabled.</li>
              <li>Data Handling: Data deletion timelines outlined in Section 17 will apply.</li>
              <li>Outstanding Payments: Any unpaid fees or charges remain due and payable.</li>
            </ul>
          </section>

          <section className="bg-white rounded-xl shadow-lg p-8">
            <h2 className="text-2xl font-bold mb-4">24. Modifications to Terms</h2>

            <p className="text-gray-700">VigilPrivacy Data reserves the right to revise, update, or modify these Terms at any time, with or without prior notice. Your continued use of the Application after such modifications constitutes your acceptance of the updated Terms. It is your responsibility to review these Terms periodically for any changes.</p>
          </section>

          <section className="bg-white rounded-xl shadow-lg p-8">
            <h2 className="text-2xl font-bold mb-4">25. Governing Law & Jurisdiction</h2>

            <p className="text-gray-700">These Terms shall be governed by and construed in accordance with the laws of India. Any disputes arising under or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts located in Hyderabad, Telangana, India.</p>
          </section>

          <section className="bg-white rounded-xl shadow-lg p-8">
            <h2 className="text-2xl font-bold mb-4">26. Dispute Resolution</h2>

            <p className="text-gray-700 mb-3">Any disputes arising under or in connection with these Terms shall be resolved through the following process:</p>

            <ul className="list-disc ml-6 text-gray-700 space-y-1">
              <li><strong>Good Faith Negotiations</strong> - The Parties shall first attempt to resolve the dispute through good faith negotiations within 15 days of written notice of the dispute.</li>
              <li><strong>Mediation (Optional)</strong> - If negotiations fail, the Parties may mutually agree to engage in mediation as a non-binding alternative dispute resolution mechanism.</li>
              <li><strong>Arbitration</strong> - If the dispute remains unresolved, it shall be finally settled by arbitration in accordance with the Arbitration and Conciliation Act, 1996, with the following conditions:
                <ul className="list-disc ml-6 text-gray-700 mt-2">
                  <li>Seat of Arbitration: Hyderabad, Telangana, India</li>
                  <li>Language: English</li>
                  <li>Arbitrator: A single arbitrator appointed mutually by the Parties</li>
                </ul>
              </li>
            </ul>

            <p className="text-gray-700 mt-3">The decision of the arbitrator shall be final and binding on both Parties.</p>
          </section>

          <section className="bg-white rounded-xl shadow-lg p-8">
            <h2 className="text-2xl font-bold mb-4">27. Notices</h2>

            <p className="text-gray-700">All notices should be sent to:</p>
            <p className="text-gray-700 mt-2">
              VigilPrivacy Data<br />
              Email: Contact@vigilprivacydata.com<br />
              Address: Please refer to registered address on website
            </p>

            <p className="text-gray-700 mt-3">Notices sent electronically are considered delivered within 24 hours.</p>
          </section>

          <section className="bg-white rounded-xl shadow-lg p-8">
            <h2 className="text-2xl font-bold mb-4">28. Entire Agreement</h2>

            <p className="text-gray-700">These Terms constitute the entire agreement between you and VigilPrivacy Data regarding your use of the Application and supersede any prior agreements, proposals, or discussions, whether written or oral, relating to the subject matter herein.</p>
          </section>

          <section className="bg-white rounded-xl shadow-lg p-8">
            <h2 className="text-2xl font-bold mb-4">29. Severability</h2>

            <p className="text-gray-700">If any provision of these Terms is found to be invalid, illegal, or unenforceable, such provision shall be deemed modified to the minimum extent necessary to make it enforceable, and the remaining provisions shall continue in full force and effect.</p>
          </section>

          <section className="bg-white rounded-xl shadow-lg p-8">
            <h2 className="text-2xl font-bold mb-4">30. Waiver</h2>

            <p className="text-gray-700">Failure by either Party to enforce any provision of these Terms shall not constitute a waiver of that provision or any other rights under this Agreement. Any waiver must be expressly stated in writing to be valid.</p>
          </section>

          <section className="bg-white rounded-xl shadow-lg p-8">
            <h2 className="text-2xl font-bold mb-4">31. Force Majeure</h2>

            <p className="text-gray-700">VigilPrivacy Data shall not be held liable for any delay or failure in performance resulting from circumstances beyond its reasonable control, including but not limited to:</p>

            <ul className="list-disc ml-6 text-gray-700 space-y-1 mt-3">
              <li>Natural disasters (e.g., earthquakes, floods, storms)</li>
              <li>Power outages or utility failures</li>
              <li>Cyber-attacks or other malicious activities</li>
              <li>Wars, civil unrest, or acts of terrorism</li>
              <li>Government regulations, restrictions, or orders</li>
              <li>Internet or telecommunications service disruptions</li>
            </ul>

            <p className="text-gray-700 mt-3">Such events shall excuse VigilPrivacy Data from its obligations for the duration of the disruption and to the extent affected.</p>
          </section>

          <section className="bg-white rounded-xl shadow-lg p-8">
            <h2 className="text-2xl font-bold mb-4">32. Assignment</h2>

            <p className="text-gray-700 mb-3">You may not assign or transfer these Terms, in whole or in part, without the prior written consent of VigilPrivacy Data.</p>

            <p className="text-gray-700">VigilPrivacy Data may assign or transfer these Terms without restriction in connection with: a merger, an acquisition, a corporate restructuring, a change of ownership or control. Any permitted assignment shall be binding upon and inure to the benefit of the parties and their respective successors and permitted assigns.</p>
          </section>

          <section className="bg-white rounded-xl shadow-lg p-8">
            <h2 className="text-2xl font-bold mb-4">33. Contact</h2>

            <p className="text-gray-700">For any queries, support, or assistance, please reach out to us at:</p>
            <p className="text-gray-700 mt-2"><strong>Email:</strong> contact@vigilprivacydata.com<br /><strong>Website:</strong> www.vigilprivacydata.com</p>
          </section>

          {/* Footer CTA */}
          <div className="flex justify-between items-center">
            <button
              onClick={() => navigate("/")}
              className="px-4 py-2 rounded-md bg-[#5DE992] text-black font-medium hover:opacity-90 transition"
            >
              ← Home
            </button>

            <a
              href="mailto:contact@vigilprivacydata.com?subject=Terms Inquiry"
              className="inline-flex items-center gap-2 bg-[#5DE992] text-black px-4 py-2 rounded-lg font-semibold hover:opacity-90 transition"
            >
              Contact Support
            </a>
          </div>
        </div>
      </div>
    </main>
  );
}
